const char help[] = "S t o i c a l  %s \n"
  "Copyright (c) 2002 Jonathan Moore Liles.\n"
  "Released under the GNU General Public License (see COPYING)\n"
  "\n"
  "usage:\n"
  "stoical [ option ] ... [ file ] [ arg ] ... \n"
  "\n"
  "The available options include:\n"
  "\n"
  "-h			- Print this help and exit.\n"
  "-v			- Print version information and exit.\n"
  "-e code			- Exectue the instructions 'code'.\n"
  "-l path			- Change STOICAL root library path.\n"
  "-f file			- Run 'file' (useful when file begins with a '-').\n"
  "\n";

